### ISSUE TITLE
关于hard negative samples的问题

### ISSUE THREAD

**Issue by Chunwei-Wu** [WangFeng18/InvariancePropagation#1]
作者您好，非常感谢您能公布代码。

在您论文Hard Sampling Strategy部分提到N_neg(i) = NM(i) − N (i)，并且background set B(i) = N_neg(i) ∪ Nh(i)。但是在objective.py中background set只是减去了self_sim。

**Comment by WangFeng18** [comment]
Sorry for the late reply.
Thanks for the detailed observation. In our paper, we have stated in the end of 3.2 that we use the Nm(i) to approximate B(i), due to the computation inefficiency of set operation which will break the parallelism in GPU. 
![image](https://user-images.githubusercontent.com/43294876/111068561-34f88e00-8504-11eb-936d-27d04a46c542.png)
Feng.
